const PROGRAM='delayed-memory';
const FALLBACK_WORDS=['가능성','책임감','집중력','상상력','불확실성','우선순위','요구사항','아키텍처','정리하다','분석하다','구조화하다','성찰하다','구체적','본질적','기억력','표현력','자신감','긴장감','호기심','목적의식'];
let wordBank=[],selectedWords=[],currentIndex=0,wordTimer=null,wordSecondsLeft=0,mathTimer=null,mathSecondsLeft=30,currentMath=null,mathTotal=0,mathCorrect=0,subCount=0,isReviewMode=false;
const setup=document.getElementById('setup-section'),memorize=document.getElementById('memorize-section'),mathSec=document.getElementById('math-section'),answerSec=document.getElementById('answer-section'),resultSec=document.getElementById('result-section');
const wordCount=document.getElementById('word-count'),wordSeconds=document.getElementById('word-seconds'),delaySeconds=document.getElementById('delay-seconds'),lengthFilter=document.getElementById('length-filter'),mathMode=document.getElementById('math-mode'),bankStatus=document.getElementById('bank-status'),reviewStatus=document.getElementById('review-status'),historyStatus=document.getElementById('history-status'),progress=document.getElementById('progress-text'),wordDisplay=document.getElementById('word-display'),wordTimerText=document.getElementById('word-timer'),mathTimerText=document.getElementById('math-timer'),mathQuestion=document.getElementById('math-question'),mathAnswer=document.getElementById('math-answer'),mathFeedback=document.getElementById('math-feedback'),answerGrid=document.getElementById('answer-grid');

document.getElementById('start-btn').addEventListener('click',()=>startTraining(false));
document.getElementById('review-btn').addEventListener('click',()=>startTraining(true));
document.getElementById('next-word-btn').addEventListener('click',showNextWord);
document.getElementById('submit-math-btn').addEventListener('click',submitMath);
document.getElementById('check-btn').addEventListener('click',checkAnswers);
mathAnswer.addEventListener('keyup',e=>{if(e.key==='Enter')submitMath();});
document.addEventListener('keyup',e=>{if(e.key==='Enter'&&!memorize.classList.contains('hidden'))showNextWord();});
delaySeconds.addEventListener('change',()=>document.getElementById('delay-label').innerText=`${delaySeconds.value}초`);
init();
async function init(){try{const r=await fetch('word-bank.json',{cache:'no-store'});if(!r.ok)throw new Error('word-bank missing');const data=await r.json();wordBank=normalizeWordData(data).map(i=>i.word);}catch(e){wordBank=FALLBACK_WORDS;}bankStatus.innerText=`${wordBank.length}개`;updateStatsPanel();}
function normalizeWordData(data){if(Array.isArray(data))return data;if(!data||!Array.isArray(data.groups))return[];const seen=new Set(),out=[];data.groups.forEach(g=>(g.words||[]).forEach(w=>{if(!seen.has(w)){seen.add(w);out.push({word:w});}}));return out;}
function filteredWords(){return wordBank.filter(w=>lengthFilter.value==='all'||(lengthFilter.value==='3plus'&&w.length>=3)||(lengthFilter.value==='4plus'&&w.length>=4));}
function updateStatsPanel(){const s=MemoryTrainer.summary(PROGRAM);reviewStatus.innerText=`오늘 복습 ${s.due}개`;historyStatus.innerText=`기록 ${s.totalSessions}회${s.lastScore!==null?` · 최근 ${s.lastScore}점`:''}`;MemoryTrainer.drawChart('history-chart',PROGRAM);}
function shuffle(a){const c=[...a];for(let i=c.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[c[i],c[j]]=[c[j],c[i]];}return c;}
function uniqueWords(items){const seen=new Set(),out=[];items.forEach(w=>{if(!seen.has(w)){seen.add(w);out.push(w);}});return out;}
function startTraining(reviewOnly){let pool;if(reviewOnly){pool=MemoryTrainer.reviewWords(PROGRAM);if(!pool.length){alert('오늘 복습할 단어가 없습니다.');return;}isReviewMode=true;}else{pool=MemoryTrainer.weightedPool(filteredWords(),PROGRAM);isReviewMode=false;}if(pool.length<3){alert('선택 조건에 맞는 단어가 부족합니다.');return;}const count=Math.min(Math.max(3,parseInt(wordCount.value,10)||3),12,pool.length);selectedWords=uniqueWords(shuffle(pool)).slice(0,count);currentIndex=0;setup.classList.add('hidden');resultSec.classList.add('hidden');answerSec.classList.add('hidden');mathSec.classList.add('hidden');memorize.classList.remove('hidden');showCurrentWord();}
function clearWordTimer(){if(wordTimer){clearInterval(wordTimer);wordTimer=null;}}
function startWordTimer(){clearWordTimer();const s=parseInt(wordSeconds.value,10);if(!s){wordTimerText.innerText='자동 넘김 꺼짐 · Enter 또는 버튼으로 이동';return;}wordSecondsLeft=s;wordTimerText.innerText=`자동 다음까지 ${wordSecondsLeft}초`;wordTimer=setInterval(()=>{wordSecondsLeft-=1;wordTimerText.innerText=`자동 다음까지 ${wordSecondsLeft}초`;if(wordSecondsLeft<=0)showNextWord();},1000);}
function showCurrentWord(){progress.innerText=`${currentIndex+1} / ${selectedWords.length}${isReviewMode?' · 복습':''}`;wordDisplay.innerText=selectedWords[currentIndex];document.getElementById('next-word-btn').innerText=currentIndex===selectedWords.length-1?'계산 방해 과제로 이동':'다음 단어 보기';startWordTimer();}
function showNextWord(){clearWordTimer();currentIndex+=1;if(currentIndex>=selectedWords.length){startMathPhase();return;}showCurrentWord();}
function startMathPhase(){memorize.classList.add('hidden');mathSec.classList.remove('hidden');mathSecondsLeft=parseInt(delaySeconds.value,10);mathTotal=0;mathCorrect=0;subCount=0;updateMathStats();mathFeedback.innerText='뺄셈이 더 자주 나옵니다. 빠르게 풀어 보세요.';makeMathProblem();mathAnswer.focus();mathTimerText.innerText=`남은 시간 ${mathSecondsLeft}초`;mathTimer=setInterval(()=>{mathSecondsLeft-=1;mathTimerText.innerText=`남은 시간 ${mathSecondsLeft}초`;if(mathSecondsLeft<=0)finishMathPhase();},1000);}
function rand(min,max){return Math.floor(Math.random()*(max-min+1))+min;}
function makeMathProblem(){const isSub=Math.random()<0.75;let a,b,answer,op;if(isSub){if(mathMode.value==='easy'){a=rand(20,79);b=rand(3,Math.min(29,a));}else{a=rand(40,99);b=rand(7,Math.min(58,a));}op='-';answer=a-b;subCount+=1;}else{if(mathMode.value==='easy'){a=rand(5,39);b=rand(3,29);}else{a=rand(18,69);b=rand(7,49);}op='+';answer=a+b;}currentMath={a,b,op,answer};mathQuestion.innerText=`${a} ${op} ${b} = ?`;mathAnswer.value='';updateMathStats();}
function submitMath(){if(mathSec.classList.contains('hidden')||!currentMath)return;const v=parseInt(mathAnswer.value,10);if(Number.isNaN(v))return;mathTotal+=1;if(v===currentMath.answer){mathCorrect+=1;mathFeedback.innerText='정답입니다.';}else{mathFeedback.innerText=`오답입니다. 정답은 ${currentMath.answer}`;}makeMathProblem();mathAnswer.focus();}
function updateMathStats(){document.getElementById('math-total').innerText=mathTotal;document.getElementById('math-correct').innerText=mathCorrect;document.getElementById('sub-count').innerText=subCount;}
function finishMathPhase(){clearInterval(mathTimer);mathTimer=null;mathSec.classList.add('hidden');showAnswerInputs();}
function showAnswerInputs(){answerSec.classList.remove('hidden');answerGrid.innerHTML='';selectedWords.forEach((_,i)=>{const input=document.createElement('input');input.type='text';input.placeholder=`${i+1}번째 기억 단어`;input.autocomplete='off';answerGrid.appendChild(input);});answerGrid.querySelector('input').focus();}
function normalize(v){return MemoryTrainer.norm(v);}
function checkAnswers(){const correctSet=new Set(selectedWords.map(normalize));const user=[...new Set(Array.from(answerGrid.querySelectorAll('input')).map(i=>normalize(i.value)).filter(Boolean))];const matched=user.filter(w=>correctSet.has(w));const missed=selectedWords.filter(w=>!matched.includes(w));MemoryTrainer.recordSession(PROGRAM,selectedWords,matched,{review:isReviewMode,delaySeconds:parseInt(delaySeconds.value,10),mathTotal,mathCorrect,subCount});resultSec.innerHTML=`<h2>${matched.length} / ${selectedWords.length}개 정답</h2><div class="score-board"><div class="score-card"><strong>${mathTotal}</strong>계산 시도</div><div class="score-card"><strong>${mathCorrect}</strong>계산 정답</div><div class="score-card"><strong>${subCount}</strong>뺄셈 출제</div></div><p><span class="correct">맞춘 단어:</span></p><div class="pill-list">${matched.length?matched.map(w=>`<span class="pill hit">${w}</span>`).join(''):'<span class="pill">없음</span>'}</div><p><span class="wrong">놓친 단어:</span></p><div class="pill-list">${missed.length?missed.map(w=>`<span class="pill miss">${w}</span>`).join(''):'<span class="pill hit">없음</span>'}</div><p><span class="wrong">내가 쓴 것:</span></p><div class="pill-list">${user.length?user.map(w=>`<span class="pill">${w}</span>`).join(''):'<span class="pill">입력 없음</span>'}</div><p class="small-note">놓친 단어는 다음 훈련에서 더 자주 나오며, 1일·3일·7일 후 복습 목록에 자동 등록됩니다.</p><div class="button-row"><button onclick="restart()">다시 하기</button></div>`;answerSec.classList.add('hidden');resultSec.classList.remove('hidden');}
function restart(){clearWordTimer();if(mathTimer)clearInterval(mathTimer);selectedWords=[];currentIndex=0;resultSec.classList.add('hidden');setup.classList.remove('hidden');updateStatsPanel();wordCount.focus();}
